[ticket]
title = "예스24 티켓"
url = "http://ticket.yes24.com/New/Notice/NoticeMain.aspx"
entrySelector = "tbody tr:not(:first-child)"
titleSelector = "td:nth-child(2)"
linkSelector = "td:nth-child(2) > a"
contentSelector = "td:nth-child(3)"
waitUntil = "networkidle"
onFail = "stale"

[ticket_m]
title = "예스24 티켓 모바일"
url = "http://m.ticket.yes24.com/Notice/List.aspx?type=1"
entrySelector = "#BoardList > li"
titleSelector = "a > div.brd_name.limit_2ln"
linkSelector = "a[class='lnk_brd']"
contentSelector = "em[class='txt']"
waitUntil = "networkidle"
onFail = "stale"

[ticket_angel]
title = "YES24 티켓 ─ 엔젤티켓"
url = "http://ticket.yes24.com/Pages/Events/HotEvent/PromotionInfo.aspx?id=2577"
entrySelector = "div.listwrap div.list"
titleSelector = "span.t_t"
linkSelector = "a"
contentSelector = "a > dl > dd > table > tbody > tr > td > table > tbody > tr:nth-child(1)"
imageSelector = "span.pos img"
waitUntil = "networkidle"
onFail = "stale"

[ticket_angel_m]
title = "YES24 티켓 ─ 엔젤티켓 모바일"
url = "http://m.ticket.yes24.com/Discount/Angel.aspx"
entrySelector = "ul.yGoodsUnit li"
titleSelector = "p.goods_name"
linkSelector = "a.lnk_goods"
contentSelector = "div.goods_info"
imageSelector = "em.imgBdr img"
waitUntil = "networkidle"
onFail = "stale"

[ticket_event]
title = "YES24 티켓 ─ 이벤트"
url = "http://ticket.yes24.com/New/Events/Main.aspx"
entrySelector = "div.event-main-list ul li"
titleSelector = "p.eve-mlist-tit"
linkSelector = "a"
contentSelector = "p.eve-mlist-txt"
imageSelector = "a img"
waitUntil = "networkidle"
onFail = "stale"

[ticket_event_m]
title = "YES24 티켓 ─ 이벤트 모바일"
url = "http://m.ticket.yes24.com/Event/List.aspx"
entrySelector = "ul.yGoodsUnit li"
titleSelector = "div.goods_info p.evt_info:nth-child(1)"
linkSelector = "a.lnk_goods"
contentSelector = "div.goods_info p.evt_info[style='display:block;']"
imageSelector = "p.goods_img em.imgBdr img"
waitUntil = "networkidle"
onFail = "stale"

[ticket_coupon]
title = "YES24 티켓 ─ 쿠폰"
url = "http://ticket.yes24.com/New/Events/Main.aspx"
entrySelector = "div.event-mclist-box"
titleSelector = "p"
linkSelector = "a"
contentSelector = "dl"
waitUntil = "networkidle"
onFail = "stale"
