[ticket]
title = "예스24 티켓"
url = "http://ticket.yes24.com/New/Notice/NoticeMain.aspx"
entrySelector = "tbody tr:not(:first-child)"
titleSelector = "td:nth-child(2)"
linkSelector = "td:nth-child(2) > a"
contentSelector = "td:nth-child(3)"
waitUntil = "networkidle"
onFail = "stale"

[ticket_m]
title = "예스24 티켓 모바일"
url = "http://m.ticket.yes24.com/Notice/List.aspx?type=1"
entrySelector = "#BoardList > li"
titleSelector = "a > div.brd_name.limit_2ln"
linkSelector = "a[class='lnk_brd']"
contentSelector = "em[class='txt']"
waitUntil = "networkidle"
onFail = "stale"

[ticket_promotion]
title = "YES24 티켓 ─ 엔젤티켓"
url = "http://ticket.yes24.com/Pages/Events/HotEvent/PromotionInfo.aspx?id=2577"
entrySelector = "div.listwrap div.list"
titleSelector = "span.t_t"
linkSelector = "a"
contentSelector = "a > dl > dd > table > tbody > tr > td > table > tbody > tr:nth-child(1)"
imageSelector = "span.pos img"
waitUntil = "networkidle"
onFail = "stale"
